# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: example.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x02\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\"\"\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\x80\x01\n\x0bMathService\x12\x30\n\x03\x41\x64\x64\x12\x13.example.AddRequest\x1a\x14.example.AddResponse\x12?\n\x08Multiply\x12\x18.example.MultiplyRequest\x1a\x19.example.MultiplyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=26
  _globals['_ADDREQUEST']._serialized_end=60
  _globals['_ADDRESPONSE']._serialized_start=62
  _globals['_ADDRESPONSE']._serialized_end=91
  _globals['_MULTIPLYREQUEST']._serialized_start=93
  _globals['_MULTIPLYREQUEST']._serialized_end=132
  _globals['_MULTIPLYRESPONSE']._serialized_start=134
  _globals['_MULTIPLYRESPONSE']._serialized_end=168
  _globals['_MATHSERVICE']._serialized_start=171
  _globals['_MATHSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
